# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-6.30
#resolver: lts-7.19 
#resolver: lts-9.14

# User packages to be built.
packages:
- '..'

extra-deps:
- directory-1.3.1.5
- containers-0.5.10.2
#- bound-2.0.1
#- cabal-doctest-1.0.3
#- hashable-1.2.6.1
#- recursion-schemes-5.0.2
#- process-1.4.3.0

