# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-6.30
compiler: ghcjs-0.2.0.9006030_ghc-7.10.3
#resolver: lts-7.19
#compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006030_ghc-7.10.3:
         url: http://ghcjs.tolysz.org/lts-6.30-9006030.tar.gz
         sha1: 2371e2ffe9e8781808b7a04313e6a0065b64ee51
#      ghcjs-0.2.1.9007019_ghc-8.0.1:
#        url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
#        sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9

# User packages to be built.
packages:
- '.'
- '../common'

extra-deps:
#- directory-1.3.1.5
#- containers-0.5.10.2
- discrimination-0.3
- promises-0.3

